# Generated by Django 4.2.4 on 2023-08-14 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.category'),
        ),
    ]
