# Generated by Django 4.2.4 on 2023-08-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0005_alter_weapon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='category',
        ),
    ]
