# Generated by Django 4.2.4 on 2023-08-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0006_remove_weapon_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weapons.category'),
            preserve_default=False,
        ),
    ]
